### ISSUE TITLE
{"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI does not match registered             redirect URI"}

### ISSUE THREAD

**Issue by 0xjorgev** [crino/instagram-ios-sdk#39]
Hi there! awesome SDK but am generating this URL and so far i only get this answer from instagram: 

my Url generated in the app: https://instagram.com/oauth/authorize?response_type=token&redirect_uri=248796138fde415ca17f4f3f7d59d43b%3A%2F%2Fauthorize&scope=basic&client_id=248796138fde415ca17f4f3f7d59d43b

the response:
{"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI does not match registered             redirect URI"}

any help would be very appreciated!

Regards,

Jorge.

**Comment by desatir7316** [comment]
same problem, i got that error too :(
btw do i need use access token if I only want to get eg. followers count?
