### ISSUE TITLE
Redirect URI does not match registered redirect URI

### ISSUE THREAD

**Issue by sairasamdani** [crino/instagram-ios-sdk#5]
I have create an app on instagram. have set redirect URI as following:
https://igCLIENT_ID://authorize

In my iPhone project's info.plist, am giving igCLIENT_ID://  in URL SCHEME. but am getting the same error again and again on login. it takes user name, password and then shows this error.

I need to add instagram to my project asap. Any help will be much appreciated.

Thank you

**Comment by iosdeveloper123** [comment]
Hi, After i given the ig[CLIENT_ID] same error is showing , kindly tell How to resolve this error in ios, please help 
{
  "error_type": "OAuthException",
  "code": 400,
  "error_message": "Redirect URI does not match registered redirect URI"
}
